import pptxgen from 'pptxgenjs';
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(process.cwd());
const paper = path.join(root, '论文相关文件', '新写的论文');
const exp = path.join(root, '.');
const pptDirs = [paper, path.join(exp, 'pptx')];
const drawDirs = [paper, path.join(exp, 'drawio')];
pptDirs.forEach(d=>fs.mkdirSync(d,{recursive:true})); drawDirs.forEach(d=>fs.mkdirSync(d,{recursive:true}));
const C={navy:'17324D',blue:'2F6B9A',red:'C4553D',grid:'CBD5E1',ink:'24313D',gray:'6E7B87',white:'FFFFFF'};
const SHAPE=(new pptxgen()).ShapeType;
const caps=['File impact','Backup','Persistence','Privilege','Process','Network','Execution','Anti-analysis','Impact chain'];
const benign=[.945,.007,.546,.176,.063,.642,.429,.430,.339], ransom=[.958,.058,.717,.535,.186,.915,.490,.644,.514];

function baseSlide(p,title,subtitle){let s=p.addSlide();s.background={color:C.white};s.addText(title,{x:.55,y:.25,w:12.2,h:.35,fontFace:'Arial',fontSize:22,bold:true,color:C.navy,margin:0});s.addText(subtitle,{x:.55,y:.67,w:12.2,h:.22,fontFace:'Arial',fontSize:11,color:C.gray,margin:0});return s;}
function axes(s,x,y,w,h,ymax=1){s.addShape(SHAPE.line,{x,y:y+h,w, h:0,line:{color:C.ink,width:1}});s.addShape(SHAPE.line,{x,y,w:0,h:-h,line:{color:C.ink,width:1}});for(let i=1;i<5;i++)s.addShape(SHAPE.line,{x,y:y+h-h*i/5,w,h:0,line:{color:C.grid,width:.5,dash:'dash'}});}
function addLegend(s,x,y){s.addShape(SHAPE.rect,{x,y,w:.16,h:.16,fill:{color:C.blue},line:{color:C.blue}});s.addText('Benign',{x:x+.22,y:y-.02,w:.7,h:.18,fontSize:9,color:C.ink,margin:0});s.addShape(SHAPE.rect,{x:x+1.05,y,w:.16,h:.16,fill:{color:C.red},line:{color:C.red}});s.addText('Ransomware',{x:x+1.27,y:y-.02,w:1.1,h:.18,fontSize:9,color:C.ink,margin:0});}

// Figure 1: two editable histogram panels (representative binned heights from the frozen SVG).
{let p=new pptxgen();p.layout='LAYOUT_WIDE';p.author='BEIST';let s=baseSlide(p,'Observation readiness and environment dependence','Editable reconstruction of the two-panel audit distribution');
  const panels=[{x:.75,title:'Report observability',vals:[.5,.8,1.2,3.9,5.4,36,.3,.1,.1,.1]},{x:6.8,title:'Environment-dependent atom rate',vals:[15.8,12.4,7.0,4.8,2.9,1.8,1.1,.7,.3,.2]}];
  panels.forEach((q,pi)=>{s.addText(q.title,{x:q.x,y:1.2,w:5.5,h:.22,fontSize:12,bold:true,color:C.ink,align:'center',margin:0});axes(s,q.x,1.55,5.5,3.45);const bw=.22; q.vals.forEach((v,i)=>{const xx=q.x+.18+i*.49;const hh=3.1*v/40;s.addShape(SHAPE.rect,{x:xx,y:4.95-hh,w:bw,h:hh,fill:{color:pi===0?C.blue:C.blue,transparency:25},line:{color:C.blue,width:.5}});const rr=pi===0?[.4,.8,1.3,3.4,4.6,32,.4,.2,.1,.1][i]:[15.9,11.8,6.8,4.7,2.6,1.6,.8,.4,.2,.1][i];const hh2=3.1*rr/40;s.addShape(SHAPE.rect,{x:xx+bw,y:4.95-hh2,w:bw,h:hh2,fill:{color:C.red,transparency:25},line:{color:C.red,width:.5}});});s.addText(pi===0?'Observation readiness':'Environment-dependent atom rate',{x:q.x,y:5.12,w:5.5,h:.22,fontSize:9,color:C.gray,align:'center',margin:0});});addLegend(s,5.1,5.65);for(const d of pptDirs)await p.writeFile({fileName:path.join(d,'fig1_audit_distributions_editable.pptx')});}

// Figure 2: grouped capability bars, all bars and labels are editable.
{let p=new pptxgen();p.layout='LAYOUT_WIDE';p.author='BEIST';let s=baseSlide(p,'Capability evidence support by label','Editable grouped bars from the frozen support-rate table');const x0=.75,y0=1.55,w=11.7,h=3.8;axes(s,x0,y0,w,h);caps.forEach((c,i)=>{const gx=x0+.32+i*1.25;const hb=h*benign[i];const hr=h*ransom[i];s.addShape(SHAPE.rect,{x:gx,y:y0+h-hb,w:.26,h:hb,fill:{color:C.blue},line:{color:C.blue}});s.addShape(SHAPE.rect,{x:gx+.29,y:y0+h-hr,w:.26,h:hr,fill:{color:C.red},line:{color:C.red}});s.addText(c,{x:gx-.12,y:y0+h+.08,w:.85,h:.48,fontSize:8,color:C.ink,rotate:315,margin:0,fit:'shrink'});});s.addText('Supported-record rate',{x:.18,y:2.8,w:.35,h:1.5,fontSize:9,color:C.gray,rotate:270,margin:0,align:'center'});addLegend(s,5.1,6.0);for(const d of pptDirs)await p.writeFile({fileName:path.join(d,'fig2_capability_support_editable.pptx')});}

// Figure 3: editable fragility histogram with cost bins.
{let p=new pptxgen();p.layout='LAYOUT_WIDE';p.author='BEIST';let s=baseSlide(p,'Capability-level evidence fragility','Editable distribution of minimum atom disruption costs');const x=.95,y=1.5,w=11,h=4.2;axes(s,x,y,w,h);const bins=[.61,.40], labels=['1 atom','2 atoms'];bins.forEach((v,i)=>{const bw=2.3;const xx=x+1.0+i*3.2;const hh=h*v/.65;s.addShape(SHAPE.rect,{x:xx,y:y+h-hh,w:bw,h:hh,fill:{color:C.blue,transparency:25},line:{color:C.blue}});s.addShape(SHAPE.rect,{x:xx,y: y+h-hh*.98,w:bw,h:hh*.98,fill:{color:C.red,transparency:30},line:{color:C.red}});s.addText(labels[i],{x:xx,y:y+h+.12,w:bw,h:.25,fontSize:10,color:C.ink,align:'center',margin:0});});s.addText('Density',{x:.25,y:2.9,w:.35,h:1,fontSize:9,color:C.gray,rotate:270,margin:0});addLegend(s,9.3,6.0);for(const d of pptDirs)await p.writeFile({fileName:path.join(d,'fig3_fragility_cost_editable.pptx')});}

const esc=x=>String(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function drawio(name,title,body){const cells=[];let id=2;const cell=(v,x,y,w,h,style)=>{const n=id++;cells.push(`<mxCell id="${n}" value="${esc(v)}" style="${style}" vertex="1" parent="1"><mxGeometry x="${x}" y="${y}" width="${w}" height="${h}" as="geometry"/></mxCell>`);return n};const edge=(a,b)=>cells.push(`<mxCell id="${id++}" edge="1" parent="1" source="${a}" target="${b}" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;strokeColor=#17324D;endArrow=block;endFill=1"><mxGeometry relative="1" as="geometry"/></mxCell>`);body(cell,edge,cells);const xml=`<mxfile host="app.diagrams.net"><diagram name="${title}"><mxGraphModel page="1" pageWidth="1600" pageHeight="900"><root><mxCell id="0"/><mxCell id="1" parent="0"/>${cells.join('')}</root></mxGraphModel></diagram></mxfile>`;for(const d of drawDirs)fs.writeFileSync(path.join(d,name),xml);}
drawio('fig1_audit_distributions_editable.drawio','Audit distributions',(cell,edge)=>{const a=cell('Readiness histogram\nBenign + ransomware',80,120,460,260,'rounded=1;whiteSpace=wrap;html=1;fillColor=#EAF1F6;strokeColor=#2F6B9A;fontColor=#17324D;fontSize=18;align=center;verticalAlign=middle');const b=cell('Environment-dependence histogram\nBenign + ransomware',650,120,520,260,'rounded=1;whiteSpace=wrap;html=1;fillColor=#FAEDED;strokeColor=#C4553D;fontColor=#17324D;fontSize=18;align=center;verticalAlign=middle');edge(a,b);});
drawio('fig2_capability_support_editable.drawio','Capability support',(cell,edge)=>{let prev=null;caps.forEach((c,i)=>{const n=cell(`${c}\nBenign ${(benign[i]*100).toFixed(1)}%\nRansomware ${(ransom[i]*100).toFixed(1)}%`,40+i*165,150,145,200,'rounded=1;whiteSpace=wrap;html=1;fillColor=#EAF1F6;strokeColor=#2F6B9A;fontColor=#17324D;fontSize=12;align=center;verticalAlign=middle');if(prev)edge(prev,n);prev=n;});});
drawio('fig3_fragility_cost_editable.drawio','Fragility histogram',(cell,edge)=>{const a=cell('Cost = 1 atom\nBenign / ransomware density',180,170,300,250,'rounded=1;whiteSpace=wrap;html=1;fillColor=#EAF1F6;strokeColor=#2F6B9A;fontColor=#17324D;fontSize=16;align=center;verticalAlign=middle');const b=cell('Cost = 2 atoms\nBenign / ransomware density',700,170,300,250,'rounded=1;whiteSpace=wrap;html=1;fillColor=#FAEDED;strokeColor=#C4553D;fontColor=#17324D;fontSize=16;align=center;verticalAlign=middle');edge(a,b);});

