import pptxgen from 'pptxgenjs';
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(process.cwd());
const out = path.join(root, '.');
const pptOut = path.join(out, 'pptx');
const drawOut = path.join(out, 'drawio');
fs.mkdirSync(pptOut, {recursive:true}); fs.mkdirSync(drawOut, {recursive:true});

const colors = {navy:'17324D', blue:'2F6B9A', teal:'2E8B86', amber:'C4872F', red:'B94A48', pale:'EAF1F6', ink:'24313D', gray:'6E7B87', white:'FFFFFF'};
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900" viewBox="0 0 1600 900"><rect width="1600" height="900" fill="#ffffff"/><text x="90" y="90" font-family="Arial" font-size="42" font-weight="700" fill="#17324d">BEIST evidence measurement protocol</text><text x="90" y="130" font-family="Arial" font-size="22" fill="#6e7b87">A deterministic path from recorded sandbox events to auditable evidence</text><g font-family="Arial"><rect x="90" y="220" rx="20" width="260" height="180" fill="#eaf1f6" stroke="#2f6b9a" stroke-width="3"/><text x="125" y="275" font-size="28" font-weight="700" fill="#17324d">Raw report</text><text x="125" y="320" font-size="21" fill="#24313d">16 JSON fields</text><text x="125" y="355" font-size="21" fill="#24313d">missingness retained</text><rect x="450" y="220" rx="20" width="260" height="180" fill="#edf6f4" stroke="#2e8b86" stroke-width="3"/><text x="485" y="275" font-size="28" font-weight="700" fill="#17324d">Atoms</text><text x="485" y="320" font-size="21" fill="#24313d">normalised event</text><text x="485" y="355" font-size="21" fill="#24313d">field provenance</text><rect x="810" y="220" rx="20" width="260" height="180" fill="#fff6e9" stroke="#c4872f" stroke-width="3"/><text x="845" y="275" font-size="28" font-weight="700" fill="#17324d">Capabilities</text><text x="845" y="320" font-size="21" fill="#24313d">S / N / I state</text><text x="845" y="355" font-size="21" fill="#24313d">corroboration</text><rect x="1170" y="220" rx="20" width="300" height="180" fill="#faeded" stroke="#b94a48" stroke-width="3"/><text x="1205" y="275" font-size="28" font-weight="700" fill="#17324d">Evidence record</text><text x="1205" y="320" font-size="21" fill="#24313d">provenance + conflicts</text><text x="1205" y="355" font-size="21" fill="#24313d">fragility profile</text><path d="M350 310 H445" stroke="#17324d" stroke-width="5" marker-end="url(#a)"/><path d="M710 310 H805" stroke="#17324d" stroke-width="5" marker-end="url(#a)"/><path d="M1070 310 H1165" stroke="#17324d" stroke-width="5" marker-end="url(#a)"/><rect x="260" y="560" rx="18" width="1080" height="170" fill="#f8fafc" stroke="#17324d" stroke-width="3"/><text x="310" y="620" font-size="28" font-weight="700" fill="#17324d">Stress testing</text><text x="310" y="665" font-size="22" fill="#24313d">admissible deletion · identifier normalisation · controlled substitution</text><text x="310" y="700" font-size="22" fill="#24313d">capability-level MEDC and Pareto-minimal disruption sets</text><path d="M940 400 C940 480 800 520 800 555" stroke="#c4872f" stroke-width="4" fill="none" marker-end="url(#b)"/><defs><marker id="a" markerWidth="12" markerHeight="12" refX="10" refY="6" orient="auto"><path d="M0,0 L12,6 L0,12 z" fill="#17324d"/></marker><marker id="b" markerWidth="12" markerHeight="12" refX="10" refY="6" orient="auto"><path d="M0,0 L12,6 L0,12 z" fill="#c4872f"/></marker></defs></g></svg>`;
fs.writeFileSync(path.join(out,'figures','beist_protocol.svg'), svg);

function addBox(slide, x,y,w,h, title, body, fill, line){
  slide.addShape(pptx.ShapeType.roundRect,{x,y,w,h,rectRadius:0.08,fill:{color:fill},line:{color:line,width:1.5}});
  slide.addText(title,{x:x+0.22,y:y+0.25,w:w-0.44,h:0.35,fontFace:'Arial',fontSize:18,bold:true,color:colors.navy,margin:0,breakLine:false});
  slide.addText(body,{x:x+0.22,y:y+0.75,w:w-0.44,h:h-0.9,fontFace:'Arial',fontSize:12,color:colors.ink,margin:0.02,breakLine:false,fit:'shrink'});
}
const pptx = new pptxgen(); pptx.layout='LAYOUT_WIDE'; pptx.author='BEIST'; pptx.subject='Editable protocol figure'; pptx.title='BEIST evidence measurement protocol';
let s = pptx.addSlide(); s.background={color:colors.white}; s.addText('BEIST evidence measurement protocol',{x:0.65,y:0.35,w:12,h:0.45,fontFace:'Arial',fontSize:25,bold:true,color:colors.navy,margin:0}); s.addText('A deterministic path from recorded sandbox events to auditable evidence',{x:0.65,y:0.82,w:12,h:0.25,fontFace:'Arial',fontSize:12,color:colors.gray,margin:0});
addBox(s,0.65,1.65,2.2,1.5,'Raw report','16 JSON fields\nmissingness retained',colors.pale,colors.blue); addBox(s,3.65,1.65,2.2,1.5,'Atoms','normalised event\nfield provenance','EDF6F4',colors.teal); addBox(s,6.65,1.65,2.2,1.5,'Capabilities','S / N / I state\ncorroboration','FFF6E9',colors.amber); addBox(s,9.65,1.65,2.55,1.5,'Evidence record','provenance + conflicts\nfragility profile','FAEDED',colors.red);
for(const [x1,x2] of [[2.85,3.55],[5.85,6.55],[8.85,9.55]]) s.addShape(pptx.ShapeType.chevron,{x:x1,y:2.25,w:x2-x1,h:0.3,fill:{color:colors.navy},line:{color:colors.navy}});
addBox(s,2.2,4.5,8.8,1.35,'Stress testing','admissible deletion · identifier normalisation · controlled substitution\ncapability-level MEDC and Pareto-minimal disruption sets','F8FAFC',colors.navy); s.addShape(pptx.ShapeType.downArrow,{x:7.4,y:3.25,w:0.35,h:1.1,fill:{color:colors.amber},line:{color:colors.amber}});
await pptx.writeFile({fileName:path.join(pptOut,'beist_protocol_editable.pptx')});

const esc = x=>String(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const cells=[]; let id=2; function cell(value,x,y,w,h,style){const c=`<mxCell id="${id++}" value="${esc(value)}" style="${style}" vertex="1" parent="1"><mxGeometry x="${x}" y="${y}" width="${w}" height="${h}" as="geometry"/></mxCell>`; cells.push(c); return id-1;}
const b1=cell('Raw report\n16 JSON fields\nmissingness retained',90,170,240,130,'rounded=1;whiteSpace=wrap;html=1;fillColor=#EAF1F6;strokeColor=#2F6B9A;fontColor=#17324D;fontSize=16;align=center;verticalAlign=middle;'); const b2=cell('Atoms\nnormalised event\nfield provenance',420,170,240,130,'rounded=1;whiteSpace=wrap;html=1;fillColor=#EDF6F4;strokeColor=#2E8B86;fontColor=#17324D;fontSize=16;align=center;verticalAlign=middle;'); const b3=cell('Capabilities\nS / N / I state\ncorroboration',750,170,240,130,'rounded=1;whiteSpace=wrap;html=1;fillColor=#FFF6E9;strokeColor=#C4872F;fontColor=#17324D;fontSize=16;align=center;verticalAlign=middle;'); const b4=cell('Evidence record\nprovenance + conflicts\nfragility profile',1080,170,280,130,'rounded=1;whiteSpace=wrap;html=1;fillColor=#FAEDED;strokeColor=#B94A48;fontColor=#17324D;fontSize=16;align=center;verticalAlign=middle;'); const st=cell('Stress testing\nadmissible perturbations\ncapability-level MEDC',390,430,650,110,'rounded=1;whiteSpace=wrap;html=1;fillColor=#F8FAFC;strokeColor=#17324D;fontColor=#17324D;fontSize=16;align=center;verticalAlign=middle;');
function edge(a,b,color){cells.push(`<mxCell id="${id++}" edge="1" parent="1" source="${a}" target="${b}" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;strokeColor=${color};strokeWidth=2;endArrow=block;endFill=1;"><mxGeometry relative="1" as="geometry"/></mxCell>`)} edge(b1,b2,'#17324D');edge(b2,b3,'#17324D');edge(b3,b4,'#17324D');edge(b3,st,'#C4872F');
const draw=`<mxfile host="app.diagrams.net" modified="2026-09-13T00:00:00.000Z" agent="BEIST" version="24.7.17"><diagram id="beist" name="BEIST protocol"><mxGraphModel dx="1600" dy="900" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1600" pageHeight="900"><root><mxCell id="0"/><mxCell id="1" parent="0"/>${cells.join('')}</root></mxGraphModel></diagram></mxfile>`;
fs.writeFileSync(path.join(drawOut,'beist_protocol_editable.drawio'),draw);

async function oneSlideDeck(file, title, subtitle, boxes){
  const p = new pptxgen(); p.layout='LAYOUT_WIDE'; p.author='BEIST'; let sl=p.addSlide(); sl.background={color:colors.white};
  sl.addText(title,{x:0.65,y:0.35,w:12,h:0.4,fontFace:'Arial',fontSize:25,bold:true,color:colors.navy,margin:0}); sl.addText(subtitle,{x:0.65,y:0.82,w:12,h:0.25,fontFace:'Arial',fontSize:12,color:colors.gray,margin:0});
  boxes.forEach((b,i)=>addBox(sl,0.8+i*3.05,2.0,2.45,1.75,b[0],b[1],b[2],b[3]));
  for(let i=0;i<boxes.length-1;i++) sl.addShape(pptx.ShapeType.chevron,{x:3.23+i*3.05,y:2.7,w:0.42,h:0.3,fill:{color:colors.navy},line:{color:colors.navy}});
  await p.writeFile({fileName:path.join(pptOut,file)});
}
await oneSlideDeck('beist_three_value_logic_editable.pptx','Three-value evidence logic','Missingness, non-support, and contradiction remain separate states.',[
  ['Supported','Sufficient recorded atoms\nfor a capability','EDF6F4',colors.teal],['Not-supported','No supporting atom\nin this record','EAF1F6',colors.blue],['Indeterminate','Observation is too sparse\nfor an evidence conclusion','FFF6E9',colors.amber],['Conflict flag','Explicitly incompatible\nclaims are recorded separately','FAEDED',colors.red]
]);
await oneSlideDeck('beist_fragility_profile_editable.pptx','Capability-level evidence fragility','Pareto-minimal record perturbations weaken each capability claim.',[
  ['Baseline claim','Capability state S\nwith provenance branches','EDF6F4',colors.teal],['Admissible fault','Delete, normalise, or\nsubstitute recorded atoms','FFF6E9',colors.amber],['MEDC vector','(atom, field, collateral)\ncost of first failure','EAF1F6',colors.blue],['EFP output','Capability-specific\nPareto frontier','FAEDED',colors.red]
]);
function drawSimple(file,title,boxes){const cs=[];let n=2;const esc2=x=>String(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');function c(v,x,y,w,h,style){cs.push(`<mxCell id="${n++}" value="${esc2(v)}" style="${style}" vertex="1" parent="1"><mxGeometry x="${x}" y="${y}" width="${w}" height="${h}" as="geometry"/></mxCell>`);return n-1;}const ids=boxes.map((b,i)=>c(b[0],80+i*300,170,240,120,`rounded=1;whiteSpace=wrap;html=1;fillColor=${b[2]};strokeColor=${b[3]};fontColor=#17324D;fontSize=16;align=center;verticalAlign=middle;`));for(let i=0;i<ids.length-1;i++)cs.push(`<mxCell id="${n++}" edge="1" parent="1" source="${ids[i]}" target="${ids[i+1]}" style="edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;strokeColor=#17324D;strokeWidth=2;endArrow=block;endFill=1;"><mxGeometry relative="1" as="geometry"/></mxCell>`);fs.writeFileSync(path.join(drawOut,file),`<mxfile host="app.diagrams.net"><diagram name="${title}"><mxGraphModel><root><mxCell id="0"/><mxCell id="1" parent="0"/>${cs.join('')}</root></mxGraphModel></diagram></mxfile>`)}
drawSimple('beist_three_value_logic_editable.drawio','Three-value evidence logic',[['Supported\nSufficient evidence','#EDF6F4','#2E8B86'],['Not-supported\nNo support in record','#EAF1F6','#2F6B9A'],['Indeterminate\nInsufficient observation','#FFF6E9','#C4872F'],['Conflict flag\nSeparate explicit contradiction','#FAEDED','#B94A48']]);
drawSimple('beist_fragility_profile_editable.drawio','Capability-level evidence fragility',[['Baseline claim\nstate S + provenance','#EDF6F4','#2E8B86'],['Admissible fault\ndelete / normalise / substitute','#FFF6E9','#C4872F'],['MEDC vector\natom, field, collateral','#EAF1F6','#2F6B9A'],['EFP output\nPareto frontier','#FAEDED','#B94A48']]);

const svgb=(title,sub,items)=>`<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="720" viewBox="0 0 1600 720"><rect width="1600" height="720" fill="#fff"/><text x="80" y="75" font-family="Arial" font-size="40" font-weight="700" fill="#17324d">${title}</text><text x="80" y="112" font-family="Arial" font-size="21" fill="#6e7b87">${sub}</text>${items.map((it,i)=>{const x=70+i*380;return `<rect x="${x}" y="220" rx="18" width="300" height="170" fill="${it[2]}" stroke="${it[3]}" stroke-width="3"/><text x="${x+28}" y="275" font-family="Arial" font-size="25" font-weight="700" fill="#17324d">${it[0]}</text><text x="${x+28}" y="320" font-family="Arial" font-size="19" fill="#24313d">${it[1]}</text>${i<items.length-1?`<path d="M${x+300} 305 H${x+365}" stroke="#17324d" stroke-width="4" marker-end="url(#a)"/>`:''}`}).join('')}<defs><marker id="a" markerWidth="12" markerHeight="12" refX="10" refY="6" orient="auto"><path d="M0,0 L12,6 L0,12 z" fill="#17324d"/></marker></defs></svg>`;
fs.writeFileSync(path.join(out,'figures','beist_three_value_logic.svg'),svgb('Three-value evidence logic','Observed evidence is separated from missingness and explicit conflict.',[['Supported','sufficient recorded atoms','#EDF6F4','#2E8B86'],['Not-supported','no support in this record','#EAF1F6','#2F6B9A'],['Indeterminate','insufficient observation','#FFF6E9','#C4872F'],['Conflict flag','incompatible claims','#FAEDED','#B94A48']]));
fs.writeFileSync(path.join(out,'figures','beist_fragility_profile.svg'),svgb('Capability-level evidence fragility','A bounded, deterministic stress test reports the first evidence failure.',[['Baseline','state S + provenance','#EDF6F4','#2E8B86'],['Perturbation','delete / normalise / substitute','#FFF6E9','#C4872F'],['MEDC','atom, field, collateral','#EAF1F6','#2F6B9A'],['EFP','Pareto frontier','#FAEDED','#B94A48']]));

